<?php
/**
 * Created by PhpStorm.
 * User: lance
 * Date: 2018/12/3 0003
 * Time: 17:51
 */

return [
    'capacitor'=>[
        [
            "name">'Samsung',
            "id"=>[63,6989],
            "boost"=>0.99,
            'code'=>'samsung',
        ],
        [
            "name">'muRata',
            "id"=>[103,6798],
            "boost"=>0.98,
            'code'=>'murata',
        ],
        [
            "name">'Yageo',
            "id"=>97,
            "boost"=>0.97,
            'code'=>'yageo',
        ],
        [
            "name">'taiyo',
            "id"=>[110,6141,6166,6188,6359,7821],
            "boost"=>0.96,
            'code'=>'taiyo',
        ],
        [
            "name">'TDK',
            "id"=>[17,6542,7525],
            "boost"=>0.95,
            'code'=>'tdk',
        ],
        [
            "name">'Walsin',
            "id"=>[160,7210],
            "boost"=>0.94,
            'code'=>'walsin',
        ],
        [
            "name">'Fenghua',
            "id"=>[4475,5280],
            "boost"=>0.93,
            'code'=>'fenghua',
        ],
        [
            "name">'Eyang',
            "id"=>5257,
            "boost"=>0.92,
            'code'=>'eyang',
        ],
        [
            "name">'Darfon',
            "id"=>3579,
            "boost"=>0.91,
            'code'=>'darfon',
        ],
    ],
    'inductance'=>[
        [
            "name">'muRata',
            "id"=>[103,6798],
            "boost"=>0.99,
            'code'=>'murata',
        ],
        [
            "name">'TDK',
            "id"=>[17,6542,7525],
            "boost"=>0.98,
            'code'=>'tdk',
        ],
        [
            "name">'Sunlord',
            "id"=>634,
            "boost"=>0.97,
            'code'=>'sunlord',
        ],
        [
            "name">'taiyo',
            "id"=>[110,6141,6166,6188,6359,7821],
            "boost"=>0.96,
            'code'=>'taiyo',
        ],
        [
            "name">'Chilisin',
            "id"=>3568,
            "boost"=>0.95,
            'code'=>'chilisin',
        ],
        [
            "name">'Fenghua',
            "id"=>[4475,5280],
            "boost"=>0.94,
            'code'=>'fenghua',
        ],
        [
            "name">'Microgate',
            "id"=>3617,
            "boost"=>0.93,
            'code'=>'microgate',
        ]
    ],
    'resistor'=>[
        [
            "name">'UniOhm',
            "id"=>520,
            "boost"=>0.99,
            'code'=>'uniohm',
        ],
        [
            "name">'Ralec',
            "id"=>532,
            "boost"=>0.98,
            'code'=>'ralec',
        ],
        [
            "name">'LIZ',
            "id"=>[7288,7881,8594],
            "boost"=>0.97,
            'code'=>'liz',
        ],
        [
            "name">'Yageo',
            "id"=>97,
            "boost"=>0.96,
            'code'=>'yageo',
        ],
        [
            "name">'Fenghua',
            "id"=>[4475,5280],
            "boost"=>0.95,
            'code'=>'fenghua',
        ],
        [
            "name">'TA-I',
            "id"=>[5932,8597],
            "boost"=>0.94,
            'code'=>'ta-i',
        ],
        [
            "name">'Walsin',
            "id"=>[160,7210],
            "boost"=>0.93,
            'code'=>'walsin',
        ],
        [
            "name">'SUP',
            "id"=>7577,
            "boost"=>0.92,
            'code'=>'sup',
        ],
        [
            "name">'ROHM Semiconductor',
            "id"=>72,
            "boost"=>0.91,
            'code'=>'rohm-semiconductor',
        ],
        [
            "name">'Panasonic',
            "id"=>2,
            "boost"=>0.90,
            'code'=>'panasonic',
        ],
    ],
    'crystal_oscillator'=>[
        [
            "name">'SiTime',
            "id"=>238,
            "boost"=>0.99,
            'code'=>'sitime',
        ],
        [
            "name">'Taitien',
            "id"=>4249,
            "boost"=>0.98,
            'code'=>'taitien',
        ],
        [
            "name">'Epson',
            "id"=>[79,7511,7805],
            "boost"=>0.97,
            'code'=>'epson',
        ],
        [
            "name">'KDS',
            "id"=>[693,3909,4067,6843],
            "boost"=>0.96,
            'code'=>'kds',
        ],
        [
            "name">'NDK',
            "id"=>[699,6801],
            "boost"=>0.95,
            'code'=>'ndk',
        ]
    ]
];